version: '3'
services:
  web:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:80:80'
    volumes:
      - /app/node_modules
      - .:/app